### ISSUE TITLE
[Enhancement] Simple and better security inspired by Wireguard.

### ISSUE THREAD

**Issue by KusakabeShi** [ntop/n2n#671]
WireGuard utilizes the following:[5]

1. Curve25519 for key exchange
2. ChaCha20 for encryption
3. Poly1305 for data authentication
4. SipHash for hashtable keys
5. BLAKE2s for hashing
6. UDP-based only.

I don't know too much about the detail of the implementation of wireguard, but I think we can use asymmetric key to communicate between each other instead preshared key among all nodes.

For example, supernode hold a peerinfo.yaml, like this:
```yaml
supernode:
  PrivateKey: aHQS6mTdu0G2jzLi9RtNyzmCAoTfsmMLEOHSICHMwlk=
edges:
  client1:
    PublicKey: j/HtUE5qErOlD5yOOoGVj4O7lLKvQzHTaoHwDQETliI=
    MacAddr: 00:01:02:00:00:00
  client2:
    PublicKey: bfoyjgfmU8jEZyX4HgHabK/yH08vKIGVMwhhJRxHC3E=
    MacAddr: 00:01:02:00:00:01
  client3:
    PublicKey: xhOVRByH+n4q6D8/0sak4qWnK3EvzgLcbSnbKs5xNRk=
    MacAddr: 00:01:02:00:00:02

```

then, in the three edge node, they will hold a private key themself, 
client1. ```uMOw2iLYQ/eFNccsoc7CNEH71QBBCk3xZgpEOe0Zi3M=```
client2. ```MH68XsFVzzIAEKlJRU2IdyJGl6klPR01EQffj4Xm2E4=```
client3. ```GBZ5+cpE8KOnSg2se9A0+c4pRQL2x6oLv44DhOREK2E=```
and initialize with supernode public key ```lNPxqERkIF9Gb4R2xGq+czb0XCx7xcdZd7KR9nSZmmM=```:

While edges wants to communicate with another edge, they just simply download the public key(the download process may encryped by supernode key pair) from supernode, and encrypt data with their public key, just like wireguard. 

Maybe wireguard are not only just encrypt data with public key, it has key exchange or other steps, we can copy all these steps to our n2n, I think it is enough for security requirements for almost all scenarios.
